/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#94442e",
        "primary-container": "#b35c44",
        "on-primary": "#ffffff",
        "on-primary-container": "#fffcff",
        "primary-fixed": "#ffdbd1",
        "primary-fixed-dim": "#ffb5a1",
        "on-primary-fixed": "#3b0900",
        "on-primary-fixed-variant": "#79301b",
        "surface": "#fcf9f6",
        "surface-dim": "#dcdad7",
        "surface-bright": "#fcf9f6",
        "surface-container": "#f0edea",
        "surface-container-low": "#f6f3f0",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#eae8e5",
        "surface-container-highest": "#e5e2df",
        "surface-variant": "#e5e2df",
        "surface-tint": "#974730",
        "on-surface": "#1b1c1a",
        "on-surface-variant": "#55433e",
        "on-background": "#1b1c1a",
        "background": "#fcf9f6",
        "tertiary": "#006195",
        "tertiary-container": "#167bb8",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#fefdff",
        "tertiary-fixed": "#cde5ff",
        "tertiary-fixed-dim": "#94ccff",
        "on-tertiary-fixed": "#001d32",
        "on-tertiary-fixed-variant": "#004b74",
        "secondary": "#4e6078",
        "secondary-container": "#cee1fe",
        "secondary-fixed": "#d2e4ff",
        "secondary-fixed-dim": "#b5c8e4",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#52647c",
        "on-secondary-fixed": "#081c32",
        "on-secondary-fixed-variant": "#36485f",
        "outline": "#88726d",
        "outline-variant": "#dbc1ba",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "terracotta-container": "#b35c44",
        "voice-blue": "#167bb8",
        "indigo-container": "#cee1fe",
        "surface-cream": "#f0edea",
        "inverse-surface": "#31302f",
        "inverse-on-surface": "#f3f0ed",
        "inverse-primary": "#ffb5a1"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "touch-target": "48px",
        "touch-target-min": "48px",
        "margin-desktop": "64px",
        "margin-mobile": "20px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "32px",
        "gutter": "16px",
        "unit": "8px"
      },
      fontFamily: {
        sans: ["Be Vietnam Pro", "sans-serif"],
        "display-lg": ["Be Vietnam Pro", "sans-serif"],
        "headline-lg": ["Be Vietnam Pro", "sans-serif"],
        "voice-assist": ["Be Vietnam Pro", "sans-serif"],
        "title-md": ["Be Vietnam Pro", "sans-serif"],
        "body-lg": ["Be Vietnam Pro", "sans-serif"],
        "body-md": ["Be Vietnam Pro", "sans-serif"],
        "label-lg": ["Be Vietnam Pro", "sans-serif"],
        "headline-lg-mobile": ["Be Vietnam Pro", "sans-serif"]
      },
      fontSize: {
        "display-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "voice-assist": ["20px", { lineHeight: "28px", fontWeight: "500" }],
        "title-md": ["22px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "26px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "700" }]
      },
      boxShadow: {
        "soft": "0 4px 20px rgba(118,45,25,0.08)",
        "soft-ambient": "0 4px 20px 0 rgba(148, 68, 46, 0.08)",
        "ai-glow": "0 0 15px 0 rgba(148, 204, 255, 0.4)",
        "tertiary-glow": "0px 0px 15px rgba(0, 97, 149, 0.3)"
      }
    },
  },
  plugins: [],
}
